In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

In [2]:
data = pd.read_csv("gas emissions.csv")
df = pd.DataFrame(data)
df

,Anzsic,Anzsic_description,Period,Data_value,Variable,Units,Gas,Status
0,ZPZ,Primary industries,2014Q1,11316,Seasonally adjusted,Kilotonnes,Carbon dioxide equivalents,P
1,ZPZ,Primary industries,2014Q2,11178,Seasonally adjusted,Kilotonnes,Carbon dioxide equivalents,P
2,ZPZ,Primary industries,2014Q3,11126,Seasonally adjusted,Kilotonnes,Carbon dioxide equivalents,P
3,ZPZ,Primary industries,2014Q4,11118,Seasonally adjusted,Kilotonnes,Carbon dioxide equivalents,P
4,ZPZ,Primary industries,2015Q1,11064,Seasonally adjusted,Kilotonnes,Carbon dioxide equivalents,P
...,...,...,...,...,...,...,...,...
1051,ZZZ,Total,2021Q1,22211,Actual,Kilotonnes,Carbon dioxide equivalents,P
1052,ZZZ,Total,2021Q2,19019,Actual,Kilotonnes,Carbon dioxide equivalents,P
1053,ZZZ,Total,2021Q3,17788,Actual,Kilotonnes,Carbon dioxide equivalents,P
1054,ZZZ,Total,2021Q4,20312,Actual,Kilotonnes,Carbon dioxide equivalents,P
1055,ZZZ,Total,2022Q1,21462,Actual,Kilotonnes,Carbon dioxide equivalents,P

In [4]:
df.isnull()

,Anzsic,Anzsic_description,Period,Data_value,Variable,Units,Gas,Status
0,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...
1051,False,False,False,False,False,False,False,False
1052,False,False,False,False,False,False,False,False
1053,False,False,False,False,False,False,False,False
1054,False,False,False,False,False,False,False,False
1055,False,False,False,False,False,False,False,False

In [5]:
print("Initial statistics:\n", df.describe())

Initial statistics:
          Data_value
count   1056.000000
mean    4991.100379
std     6399.422212
min       59.000000
25%      531.500000
50%     2028.500000
75%     6597.500000
max    23277.000000

In [6]:
print("Variable descriptions:\n", df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1056 entries, 0 to 1055
Data columns (total 8 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Anzsic              1056 non-null   object
 1   Anzsic_description  1056 non-null   object
 2   Period              1056 non-null   object
 3   Data_value          1056 non-null   int64
 4   Variable            1056 non-null   object
 5   Units               1056 non-null   object
 6   Gas                 1056 non-null   object
 7   Status              1056 non-null   object
dtypes: int64(1), object(7)
memory usage: 66.1+ KB
Variable descriptions:
 None

In [7]:
print("Dimensions of the dataframe:", df.shape)

Dimensions of the dataframe: (1056, 8)

In [8]:
# Check data types
print("Data types:\n", df.dtypes)

Data types:
 Anzsic                object
Anzsic_description    object
Period                object
Data_value             int64
Variable              object
Units                 object
Gas                   object
Status                object
dtype: object

In [11]:
# Convert 'Data_value' column to numeric type
df['Data_value'] = pd.to_numeric(df['Data_value'], errors='coerce')

In [12]:
# Using one-hot encoding for 'Anzsic_description' column
df_encoded = pd.get_dummies(df, columns=['Anzsic_description'])

In [13]:
# Display the updated dataframe
print("Updated dataframe with one-hot encoding:\n", df_encoded.head())

Updated dataframe with one-hot encoding:
   Anzsic  Period  Data_value             Variable       Units  \
0    ZPZ  2014Q1       11316  Seasonally adjusted  Kilotonnes
1    ZPZ  2014Q2       11178  Seasonally adjusted  Kilotonnes
2    ZPZ  2014Q3       11126  Seasonally adjusted  Kilotonnes
3    ZPZ  2014Q4       11118  Seasonally adjusted  Kilotonnes
4    ZPZ  2015Q1       11064  Seasonally adjusted  Kilotonnes

                          Gas Status  \
0  Carbon dioxide equivalents      P
1  Carbon dioxide equivalents      P
2  Carbon dioxide equivalents      P
3  Carbon dioxide equivalents      P
4  Carbon dioxide equivalents      P

   Anzsic_description_Agriculture, forestry, fishing  \
0                                              False
1                                              False
2                                              False
3                                              False
4                                              False

   Anzsic_description_Construction  \
0                            False
1                            False
2                            False
3                            False
4                            False

   Anzsic_description_Electricity, gas, water, and waste services  ...  \
0                                              False               ...
1                                              False               ...
2                                              False               ...
3                                              False               ...
4                                              False               ...

   Anzsic_description_Manufacturing  Anzsic_description_Mining  \
0                             False                      False
1                             False                      False
2                             False                      False
3                             False                      False
4                             False                      False

   Anzsic_description_Other  Anzsic_description_Primary industries  \
0                     False                                   True
1                     False                                   True
2                     False                                   True
3                     False                                   True
4                     False                                   True

   Anzsic_description_Service industries  \
0                                  False
1                                  False
2                                  False
3                                  False
4                                  False

   Anzsic_description_Services excluding transport, postal, and warehousing  \
0                                              False
1                                              False
2                                              False
3                                              False
4                                              False

   Anzsic_description_Total  Anzsic_description_Total industry  \
0                     False                              False
1                     False                              False
2                     False                              False
3                     False                              False
4                     False                              False

   Anzsic_description_Transport  \
0                         False
1                         False
2                         False
3                         False
4                         False

   Anzsic_description_Transport, postal, and warehousing
0                                              False
1                                              False
2                                              False
3                                              False
4                                              False

[5 rows x 23 columns]

In [15]:
df_encoded

,Anzsic,Period,Data_value,Variable,Units,Gas,Status,"Anzsic_description_Agriculture, forestry, fishing",Anzsic_description_Construction,"Anzsic_description_Electricity, gas, water, and waste services",...,Anzsic_description_Manufacturing,Anzsic_description_Mining,Anzsic_description_Other,Anzsic_description_Primary industries,Anzsic_description_Service industries,"Anzsic_description_Services excluding transport, postal, and warehousing",Anzsic_description_Total,Anzsic_description_Total industry,Anzsic_description_Transport,"Anzsic_description_Transport, postal, and warehousing"
0,ZPZ,2014Q1,11316,Seasonally adjusted,Kilotonnes,Carbon dioxide equivalents,P,False,False,False,...,False,False,False,True,False,False,False,False,False,False
1,ZPZ,2014Q2,11178,Seasonally adjusted,Kilotonnes,Carbon dioxide equivalents,P,False,False,False,...,False,False,False,True,False,False,False,False,False,False
2,ZPZ,2014Q3,11126,Seasonally adjusted,Kilotonnes,Carbon dioxide equivalents,P,False,False,False,...,False,False,False,True,False,False,False,False,False,False
3,ZPZ,2014Q4,11118,Seasonally adjusted,Kilotonnes,Carbon dioxide equivalents,P,False,False,False,...,False,False,False,True,False,False,False,False,False,False
4,ZPZ,2015Q1,11064,Seasonally adjusted,Kilotonnes,Carbon dioxide equivalents,P,False,False,False,...,False,False,False,True,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1051,ZZZ,2021Q1,22211,Actual,Kilotonnes,Carbon dioxide equivalents,P,False,False,False,...,False,False,False,False,False,False,True,False,False,False
1052,ZZZ,2021Q2,19019,Actual,Kilotonnes,Carbon dioxide equivalents,P,False,False,False,...,False,False,False,False,False,False,True,False,False,False
1053,ZZZ,2021Q3,17788,Actual,Kilotonnes,Carbon dioxide equivalents,P,False,False,False,...,False,False,False,False,False,False,True,False,False,False
1054,ZZZ,2021Q4,20312,Actual,Kilotonnes,Carbon dioxide equivalents,P,False,False,False,...,False,False,False,False,False,False,True,False,False,False
1055,ZZZ,2022Q1,21462,Actual,Kilotonnes,Carbon dioxide equivalents,P,False,False,False,...,False,False,False,False,False,False,True,False,False,False